# Streamlit Configuration for Local Agent Collaboration System
# Updated configuration compatible with Streamlit 1.46+

[server]
# Server configuration
port = 8501
address = "localhost"
headless = false
runOnSave = false

# File watching
fileWatcherType = "auto"
enableXsrfProtection = false
enableCORS = true

# Performance settings
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration for the Streamlit app
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
