# Streamlit Configuration for Local Agent Collaboration System
# Save this as .streamlit/config.toml in your project directory

[server]
# Server configuration
port = 8501
address = "localhost"
headless = false
runOnSave = false
allowRunOnSave = false

# File watching
fileWatcherType = "auto"
enableCORS = false
enableXsrfProtection = true

# Performance settings
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration for the Streamlit app
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[global]
# Global configuration
disableWatchdogWarning = true
developmentMode = false
logLevel = "info"

# Sharing
showWarningOnDirectExecution = true

[client]
# Client configuration
caching = true
displayEnabled = true
toolbarMode = "auto"
